# Generated by Django 3.1.1 on 2020-10-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='code',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
